import argparse
from pathlib import Path
from collections import defaultdict


SECTION_ADDED = "ADDED"
SECTION_MODIFIED = "MODIFIED"
SECTION_DELETED = "DELETED"
KNOWN_SECTIONS = (SECTION_ADDED, SECTION_MODIFIED, SECTION_DELETED)


def parse_changes_file(changes_path: Path) -> set[tuple[str, str]]:
    """Parse output generated by get-changes.py into unique (section, path) pairs."""
    entries = set()
    current_section = None

    with changes_path.open("r", encoding="utf-8") as f:
        for raw_line in f:
            line = raw_line.strip()
            if not line:
                continue

            if line.startswith("//"):
                continue

            if line.startswith("[") and "]:" in line:
                section_name = line[1:].split("]:", 1)[0].strip()
                if section_name in KNOWN_SECTIONS:
                    current_section = section_name
                continue

            if current_section not in KNOWN_SECTIONS:
                continue

            if ":" not in line:
                continue

            rel_path = line.split(":", 1)[0].strip()
            if rel_path:
                entries.add((current_section, rel_path))

    return entries


def group_by_section(entries: set[tuple[str, str]]) -> dict[str, list[str]]:
    grouped = defaultdict(list)
    for section, rel_path in sorted(entries, key=lambda item: (item[0], item[1].lower(), item[1])):
        grouped[section].append(rel_path)
    return grouped


def build_report(
    only_in_first: set[tuple[str, str]],
    only_in_second: set[tuple[str, str]],
    first_name: str,
    second_name: str,
) -> str:
    lines = []
    lines.append("// ==== CHANGES DIFF ====")
    lines.append(f"// {first_name} vs {second_name}")

    def append_block(title: str, entries: set[tuple[str, str]]) -> None:
        grouped = group_by_section(entries)
        count = len(entries)
        lines.append("")
        lines.append(f"[{title}]: {count}")
        for section in KNOWN_SECTIONS:
            section_items = grouped.get(section, [])
            if not section_items:
                continue
            lines.append("")
            lines.append(f"[{section}]: {len(section_items)}")
            max_len = max(len(path) for path in section_items)
            for rel_path in section_items:
                lines.append(f"{rel_path:<{max_len}}")

    append_block("ONLY_IN_FIRST", only_in_first)
    append_block("ONLY_IN_SECOND", only_in_second)

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Compare two text outputs generated by get-changes.py and print "
            "entries that exist only in one file."
        )
    )
    parser.add_argument("first_changes", help="First changes file generated by get-changes.py")
    parser.add_argument("second_changes", help="Second changes file generated by get-changes.py")
    parser.add_argument("--output-file", help="Redirect diff output to the file")
    args = parser.parse_args()

    first_path = Path(args.first_changes).resolve()
    second_path = Path(args.second_changes).resolve()

    if not first_path.exists() or not first_path.is_file():
        raise SystemExit(f"First changes file does not exist or is not a file: {first_path}")
    if not second_path.exists() or not second_path.is_file():
        raise SystemExit(f"Second changes file does not exist or is not a file: {second_path}")

    first_entries = parse_changes_file(first_path)
    second_entries = parse_changes_file(second_path)

    only_in_first = first_entries - second_entries
    only_in_second = second_entries - first_entries

    report = build_report(only_in_first, only_in_second, first_path.name, second_path.name)

    if args.output_file:
        output_file_path = Path(args.output_file).resolve()
        with output_file_path.open("w", encoding="utf-8") as f:
            f.write(report)
        print(f"Diff report was written to '{output_file_path}'")
    else:
        print(report)


if __name__ == "__main__":
    main()
